language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t lahiruinme/docker-frontend -f Dockerfile.dev .

script:
    - docker run lahiruinme/docker-frontend npm run test -- --coverage