language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t lahiruinme/docker-frontend -f Dockerfile.prod .

#script:
 #   - docker run lahiruinme/docker-frontend npm run test -- --coverage

deploy:
    provider: "elasticbeanstalk"
    region: "ap-southeast-1"
    app: "docker"
    env: "docker-frontend"
    bucket_name: "elasticbeanstalk-ap-southeast-1-483840613156"
    bucket_path: "docker-frontend"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY